// sequence
export const LOCAL_SEQUENCE_LOADED = 'LOCAL_SEQUENCE_LOADED';

// Gfycat user
export const GFYCAT_AUTH_SUCCEEDED = 'GFYCAT_AUTH_SUCCEEDED';
export const GFYCAT_AUTH_FAILED = 'GFYCAT_AUTH_FAILED';
export const GFYCAT_USER_INFO_FETCHED = 'GFYCAT_USER_INFO_FETCHED';

// gfycat meta
export const GFYCAT_CREATION_INITIATED = 'GFYCAT_CREATION_INITIATED';
export const GFYCAT_CREATION_FAILED = 'GFYCAT_CREATION_FAILED';
export const GFYCAT_CREATION_SUCCEEDED = 'GFYCAT_CREATION_SUCCEEDED';

// image meta
export const GFYCAT_CREATION_PROPS_UPDATED = 'GFYCAT_CREATION_PROPS_UPDATED';

// draw settings
export const STROKE_WIDTH_SELECTED = 'STROKE_WIDTH_SELECTED';
export const STROKE_COLOR_SELECTED = 'STROKE_COLOR_SELECTED';

// filter settins
export const FILTER_SELECTED = 'FILTER_SELECTED';
export const FILTER_SUCCEEDED = 'FILTER_SUCCEEDED';

// select/unselect new tool
export const TOOL_SELECTED = 'TOOL_SELECTED';

// Image conversion
export const CONVERSION_STARTED = 'CONVERSION_STARTED';
export const CONVERSION_SUCCEEDED = 'CONVERSION_SUCCEEDED';

